import React, {FC} from "react";
import Head from "next/head";

interface MetaProps {}

const MetaLayout: FC<MetaProps> = ({}) => {
    return (
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
            <link rel="stylesheet" href="/assets/css/bootstrap-icons.css" />
        </Head>
    );
};

export default MetaLayout;
